user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {}

http {
  upstream frontend {
    server client:80;
  }

  upstream backend {
    server server:8000;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://frontend;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location /api/ {
      proxy_pass http://backend;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
    }
  }
}
